/**
 * Libellés de l'admin, en français seulement. Exception explicite à la règle des cinq
 * langues (décision du 16 septembre 2026) : une seule personne voit ces écrans. Ils vivent
 * ici et non dans `messages/`, sinon le test de parité exigerait quatre traductions inutiles.
 */
export const L = {
  nav: { overview: 'Vue d’ensemble', apps: 'IA', compare: 'Comparer les IA', people: 'Personnes', spend: 'Dépenses', affiliates: 'Affiliés', studio: 'Studio', creators: 'Créateurs', inbox: 'Boîte', settings: 'Réglages', backToHub: 'Retour au hub' },
  overview: {
    title: 'Vue d’ensemble',
    people: 'Personnes',
    activeToday: 'actives aujourd’hui',
    activeWeek: 'cette semaine',
    activeMonth: 'ce mois',
    signups: 'Inscriptions',
    messages: 'Messages',
    cost: 'Coût IA',
    costMonth: 'ce mois',
    subscribers: 'Abonnés',
    inTrial: 'en semaine d’accueil',
    reports: 'Signalements à traiter',
    funnel: 'Entonnoir',
    cohorts: 'Cohortes',
    health: 'Santé',
    quality: 'Qualité',
    activity: 'Activité sur 14 jours',
    revenue: 'Revenu',
    mrr: 'Revenu mensuel',
    costRatio: 'Coût IA / revenu',
    costRatioSub: 'Seuil de vigilance : 30 %',
    costRatioAlert: 'Au-dessus de 30 % : serrer les plafonds du gratuit ou la semaine d’accueil (réglages).',
    arpu: 'par abonné et par mois',
    bundleShare: 'en bundle',
    freeTier: 'Gratuit et offre de bienvenue',
    welcomeConversion: 'Convertis dans les 72 h',
    welcomeConversionSub: 'inscrits sur 30 jours',
    offerUsed: 'avec l’offre',
    lateConversion: 'Convertis après les 72 h',
    lateConversionSub: 'part des inscrits sur 30 jours qui ont payé plus tard',
    activeFree: 'Gratuits actifs aujourd’hui',
    limitHit: 'ont touché la limite du jour',
    freeCost: 'Coût IA du gratuit, 14 jours',
    freeCostSub: 'personnes qui n’ont jamais payé',
    videos: 'vidéos regardées',
    conversion: 'Conversion semaine → payant',
    conversionSub: 'semaines d’accueil terminées',
    churn: 'Attrition du mois',
    churnSub: 'abonnés au 1er',
    margin: 'Marge par abonné',
    marginSub: 'revenu moins coût IA moyen, le coût étant en dollars',
    visits: 'Visites du hub',
    visitors: 'visiteurs distincts',
    attribution: 'D’où viennent les onboardings',
  },
  attribution: { source: 'Source', campaign: 'Campagne', onboardings: 'Onboardings', direct: 'direct', empty: 'Aucun onboarding avec une origine connue.' },
  compare: {
    title: 'Comparer les IA',
    app: 'IA',
    people: 'Personnes',
    active7: 'Actifs 7 j',
    messages7: 'Messages 7 j',
    cost7: 'Coût 7 j',
    retention: 'Rétention J7',
    thumbs: 'Pouces haut',
    subscribers: 'Abonnés',
    verdict: 'Verdict',
    empty: 'Aucune IA n’a encore de données.',
  },
  settings: {
    title: 'Réglages à chaud',
    intro: 'Appliqués à la requête suivante, sans redéploiement. Un réglage qui casserait la configuration d’une IA est refusé.',
    tools: 'Outils',
    toolOn: 'actif',
    toolOff: 'coupé',
    plans: 'Plafonds de plan',
    free: 'Gratuit',
    paid: 'Abonné',
    messagesPerDay: 'Messages par jour',
    messagesPerMonth: 'Messages par mois',
    artifactsPerMonth: 'Productions par mois',
    checkinsActive: 'Rappels actifs',
    maxUsdPerDay: 'Coût IA par jour ($)',
    maxUsdPerMonth: 'Coût IA par mois ($)',
    override: 'surcharge',
    default: 'valeur de base',
    save: 'Enregistrer',
    reset: 'Revenir à la base',
    saved: 'Enregistré.',
    failed: 'Refusé : ',
    current: 'Réglages posés',
    none: 'Aucun réglage à chaud. Tout vient du code et des manifestes.',
    scopeAll: 'toutes les IA',
    promoTitle: 'Fenêtre promo',
    promoIntro: 'Pro à moitié prix le premier mois pour tous les gratuits, entre deux dates, toutes IA. Même coupon que l’offre de bienvenue. Vide = aucune fenêtre.',
    promoFrom: 'Du',
    promoUntil: 'Au',
    promoOpen: 'Ouvrir la fenêtre',
    promoClose: 'Fermer la fenêtre',
    promoActive: 'Fenêtre ouverte jusqu’au',
    promoNone: 'Aucune fenêtre ouverte.',
    welcomeTitle: 'Offre de bienvenue',
    welcomeHours: 'Durée après l’inscription (heures, 0 = éteinte)',
  },
  actions: {
    title: 'Actions',
    tester: 'Testeur',
    testerOn: 'Retirer le rôle de testeur',
    testerOff: 'Passer testeur',
    testerHint: 'Voit les IA privées, sans privilège de plan.',
    creator: 'Créateur Studio',
    creatorOn: 'Retirer l’accès créateur',
    creatorOff: 'Ouvrir l’espace créateur',
    creatorHint: 'Peut créer, tester et soumettre une IA dans /studio/mon-ia.',
    extendTrial: 'Prolonger la semaine d’accueil',
    extendDays: 'jours',
    gift: 'Offrir un mois',
    giftHint: 'Trente jours du plan payant sur toutes les IA, sans carte.',
    resetQuota: 'Remettre les quotas à zéro',
    resetHint: 'L’usage d’avant ne compte plus. Les lignes de coût restent.',
    export: 'Exporter ses données',
    exportHint: 'Un fichier JSON avec tout ce que la base sait d’elle (RGPD, portabilité).',
    delete: 'Supprimer le compte',
    deleteHint: 'Irréversible. Clerk, profils, souvenirs, conversations, productions. L’usage reste, anonyme.',
    deleteConfirm: 'Retape l’email du compte pour confirmer',
    done: 'Fait.',
    failed: 'Échec : ',
    quotaResetAt: 'Quotas remis à zéro le',
  },
  funnel: { started: 'Compte', onboarded: 'Onboarding', firstMessage: '1er message', threeMessages: '3 messages', subscribed: 'Abonné' },
  cohorts: { week: 'Semaine', signups: 'Inscrits', d1: 'J1', d7: 'J7', d30: 'J30', tooEarly: 'trop tôt', empty: 'Aucune inscription pour l’instant.' },
  quality: {
    app: 'IA',
    answers: 'Réponses',
    thumbs: 'Pouces',
    generic: 'Génériques',
    tools: 'Outils',
    toolFailed: 'échecs',
    fallbacks: 'Replis',
    quotaHits: 'Murs',
    openReports: 'Signalements',
    latency: 'Latence',
    p50: 'médiane',
    p95: 'p95',
  },
  app: {
    verdict: 'Verdict',
    retentionD7: 'Rétention J7',
    target: 'objectif',
    signups: 'Inscriptions',
    launched: 'Lancée le',
    reviewDue: 'Revue due le',
    notLaunched: 'Pas encore lancée',
    tools: 'Outils',
    green: 'Ça tient',
    orange: 'À surveiller',
    red: 'À trancher',
    grey: 'Trop tôt',
  },
  spend: {
    title: 'Dépense IA par personne',
    intro: 'Ce que chaque personne coûte en IA, par IA et par plan, sur 30 jours. Rouge : au-dessus du plafond mensuel d’un abonné (3,50 $). La règle des 50 % se lit ici.',
    allApps: 'Toutes les IA',
    mostFirst: 'Les plus chers d’abord',
    leastFirst: 'Les moins chers d’abord',
    people: 'Personnes actives (30 j)',
    free: 'gratuits',
    paid: 'abonnés',
    average: 'Coût moyen sur 30 jours',
    max: 'Le plus cher',
    min: 'le moins cher',
    total: 'Coût total 30 jours',
    totalSub: 'toutes les personnes listées',
    table: 'Personne par personne',
    messages: 'Messages 30 j',
    today: 'Aujourd’hui',
    days30: '30 jours',
    perDay: 'Par jour',
    empty: 'Aucun message sur 30 jours.',
    plans: { free: 'Gratuit', paid: 'Abonné', bundle: 'Bundle' },
  },
  studio: {
    title: 'Flowear Studio',
    intro: 'Les créateurs inscrits sur la liste d’attente, les plus récents d’abord. La première promo se choisit ici, à la main : audience réelle, idée qui suit la personne dans le temps.',
    total: 'Inscrits',
    week: 'cette semaine',
    idea: 'Idée',
    audience: 'Audience',
    origin: 'Origine',
    empty: 'Personne pour l’instant.',
    review: 'File de revue',
    nameCol: 'Nom',
    statusCol: 'Statut',
    slugCol: 'Adresse',
    reviewIntro: 'Les IA soumises par les créateurs, par ancienneté. Chaque publication passe par la liste de contrôle, cochée à la main.',
    pending: 'À relire',
    live: 'En ligne',
    account: 'Fiche',
    noAccount: 'Pas de compte',
    status: { draft: 'Brouillon', submitted: 'Soumise', in_review: 'En revue', changes_requested: 'Changements demandés', published: 'En ligne', suspended: 'Suspendue' },
    version: 'Version',
    owner: 'Créateur',
    submittedAt: 'Soumise le',
    checks: 'Vérifications automatiques',
    manifest: 'Manifeste',
    persona: 'Persona',
    questions: 'Questions d’onboarding',
    tools: 'Outils',
    suggestions: 'Suggestions',
    knowledge: 'Connaissances',
    sandbox: 'Bac à sable (le brouillon, comme le créateur le voit)',
    checklist: 'Liste de contrôle avant publication',
    shareFixed: 'Partage : 50 % du revenu net au créateur, dans tous les cas.',
    approve: 'Publier',
    approveHint: 'Tout coché, sinon le bouton reste gris. Publie, recharge le registre, envoie l’email.',
    changes: 'Demander des changements',
    changesHint: 'Motif obligatoire, envoyé au créateur. Son brouillon redevient modifiable.',
    suspend: 'Suspendre',
    suspendHint: 'Retire l’IA du hub sur-le-champ. Les abonnés en cours sont servis jusqu’à la fin de période.',
    notes: 'Motif',
    lastNotes: 'Dernier motif envoyé',
    emailSent: 'Email envoyé au créateur.',
    emailSkipped: 'Pas d’email : Resend absent ou créateur sans adresse.',
    emptyQueue: 'Rien à relire.',
    toolRequests: 'Demandes d’outils',
    toolStatus: { open: 'Ouverte', planned: 'Prévue', done: 'Faite', declined: 'Refusée' },
    noToolRequests: 'Aucune demande.',
    assessmentBrief: 'Questionnaire décrit par le créateur',
    assessmentBuilt: 'Questionnaire construit par Flowear',
    assessmentBuildHint: 'JSON du schéma « assessment » (tableau), avec « source » pour chaque questionnaire. Il entre dans le brouillon du créateur, qui le voit dans son espace.',
    assessmentSave: 'Poser dans le brouillon',
    assessmentClear: 'Retirer',
    assessmentJsonInvalid: 'JSON invalide.',
  },
  creators: {
    title: 'Créateurs',
    intro: 'Les IA des créateurs : ce qu’elles font, ce qu’elles ont rapporté, ce que tu dois. Une part devient due 30 jours après le paiement ; « Reste à verser » tient compte des versements enregistrés.',
    live: 'En ligne',
    grossMonth: 'Encaissé ce mois',
    balance: 'Reste à verser',
    pending: 'En attente',
    empty: 'Aucune IA de créateur soumise pour l’instant.',
    app: 'IA',
    owner: 'Créateur',
    status: 'Statut',
    people: 'Inscrits',
    active7: 'Actifs 7 j',
    subscribers: 'Abonnés',
    gross: 'Encaissé',
    share: 'Part créateur',
    back: 'Créateurs',
    fullStats: 'Statistiques complètes',
    review: 'Fiche de revue',
    money: 'Revenus mois par mois',
    payouts: 'Versements',
    payoutsEmpty: 'Aucun versement enregistré.',
    payoutAdd: 'Enregistrer un versement',
    payoutAmount: 'Montant (€)',
    payoutDate: 'Date',
    payoutNote: 'Note (optionnel)',
    payoutSave: 'Enregistrer',
    link: 'Lien de statistiques pour le créateur',
    linkIntro: 'Une seule page, en lecture seule, sans compte : les totaux ci-dessous (aperçu), rien d’autre. Le lien n’est affiché qu’une fois, à sa création : seule son empreinte est gardée. Régénérer ou révoquer rend l’ancien lien mort.',
    linkNone: 'Aucun lien actif.',
    linkActive: 'Lien actif depuis le',
    linkCreate: 'Créer le lien',
    linkRegenerate: 'Régénérer le lien',
    linkRevoke: 'Révoquer',
    linkCopy: 'Copier',
    linkCopied: 'Copié',
    linkShown: 'Copie-le maintenant : il ne sera plus affiché.',
    preview: 'Aperçu : ce que voit le créateur',
    colMonth: 'Mois',
    colPaying: 'Payants',
    colNet: 'Net',
    colDue: 'Dû',
    colDate: 'Date',
    colAmount: 'Montant',
    colNote: 'Note',
    noPayments: 'Pas encore de paiement.',
    summary: (t: { shareEur: string; dueEur: string; paidEur: string; balanceEur: string; pendingEur: string; advanceEur: string | null }) =>
      `Part totale ${t.shareEur} · dû ${t.dueEur} · versé ${t.paidEur} · reste à verser ${t.balanceEur} · en attente ${t.pendingEur}${t.advanceEur ? ` · versé en avance ${t.advanceEur}` : ''}`,
    revenueAndLink: 'IA de créateur : revenus, versements et lien de statistiques',
  },
  affiliates: {
    title: 'Affiliés',
    intro: (days: number) => `Un créateur, un code, un lien. Une commission par abonné payant, due ${days} jours après le premier paiement (délai de rétractation passé). Paiement à la main, une fois par mois.`,
    signups: 'Inscrits',
    appSlug: 'Limité à une IA (optionnel)',
    paying: 'Payants',
    eligible: 'Éligibles',
    due: 'Dû',
    dueSub: 'commissions à verser',
    pending: 'En attente',
    revenue: 'Encaissé',
    terms: 'Commission',
    fixedTerms: (amount: string) => `${amount} par abonné`,
    percentTerms: (percent: number, months: number | null) => `${percent} % ${months === null ? 'à vie' : `pendant ${months} mois`}`,
    mode: 'Mode',
    modeFixed: 'Fixe par abonné',
    modePercent: 'Pourcentage des paiements',
    percent: 'Part (%)',
    months: 'Mois (vide = à vie)',
    unknownRefs: (n: number) => `${n} inscription(s) avec un code inconnu`,
    addTitle: 'Ajouter un créateur',
    addIntro: 'Le code devient le lien flowear.app/amorce?ref=<code>. Minuscules, chiffres, tirets.',
    code: 'Code',
    name: 'Nom',
    contact: 'Contact',
    link: 'Lien',
    payout: 'Montant (€)',
    add: 'Ajouter',
    created: 'Créateur ajouté.',
    table: 'Créateur par créateur',
    empty: 'Aucun créateur pour l’instant.',
  },
  people: {
    title: 'Personnes',
    search: 'Chercher un email',
    email: 'Email',
    locale: 'Langue',
    createdAt: 'Inscrite le',
    noEmail: 'sans email',
    empty: 'Personne ne correspond.',
    tabs: { summary: 'Résumé', timeline: 'Frise', conversations: 'Conversations', memory: 'Mémoire', reports: 'Retours' },
    plan: 'Plan',
    trial: 'Semaine d’accueil',
    trialUntil: 'jusqu’au',
    devices: 'Appareils avec notifications',
    lastSeen: 'Dernier message',
    never: 'jamais',
    cost: 'Coût cumulé',
    perApp: 'Par IA',
    messages: 'messages',
    notes: 'souvenirs',
    artifacts: 'productions',
    profile: 'Profil',
    onboardingPending: 'onboarding non terminé',
    openConversation: 'Ouvrir le contenu',
    readNotice: 'Chaque ouverture est journalisée avec ton identifiant. N’ouvre que si tu as une raison.',
    noConversations: 'Aucune conversation.',
    noEvents: 'Aucun événement.',
    noReports: 'Aucun retour.',
    thumbsUp: 'pouces haut',
    thumbsDown: 'pouces bas',
    generic: 'génériques',
  },
  inbox: {
    title: 'Boîte',
    all: 'Tous',
    new: 'Nouveaux',
    seen: 'Vus',
    resolved: 'Résolus',
    empty: 'Rien à traiter.',
    markSeen: 'Marquer vu',
    resolve: 'Résoudre',
    resolutionPlaceholder: 'Note de résolution (facultative)',
    openPerson: 'Voir la personne',
    openConversation: 'Voir la conversation',
    source: { message: 'Réponse signalée', contact: 'Message libre', review: 'Avis', system: 'Automatique' },
    severity: { high: 'Haute', medium: 'Moyenne', low: 'Basse' },
    status: { new: 'Nouveau', seen: 'Vu', resolved: 'Résolu' },
    category: {
      false: 'Faux',
      dangerous: 'Dangereux',
      inappropriate: 'Déplacé',
      other: 'Autre',
      bug: 'Bug',
      payment: 'Paiement',
      question: 'Question',
      review: 'Avis',
      stripe_dispute: 'Litige Stripe',
      stripe_payment_failed: 'Paiement échoué',
      cost_alert: 'Alerte coût',
      error_spike: 'Pic d’erreurs',
      provider_fallback: 'Repli fournisseur',
    } as Record<string, string>,
    push: { title: 'Notifications admin', hint: 'Reçois les signalements graves sur ce téléphone.' },
  },
  events: {
    signup: 'Compte créé',
    onboarding_done: 'Onboarding terminé',
    message_sent: 'Message envoyé',
    tool_called: 'Outil appelé',
    tool_failed: 'Outil en échec',
    artifact_created: 'Production créée',
    feedback: 'Pouce',
    memory_saved: 'Souvenir noté',
    quota_hit: 'Mur atteint',
    trial_started: 'Semaine d’accueil ouverte',
    digest_sent: 'Digest envoyé',
    checkout_started: 'Paiement commencé',
    subscribed: 'Abonnement pris',
    churned: 'Abonnement arrêté',
    cost_alert: 'Alerte coût',
    provider_fallback: 'Repli de fournisseur',
    auth_denied: 'Accès refusé',
    rate_limited: 'Trop de requêtes',
    push_enabled: 'Notifications activées',
    push_disabled: 'Notifications coupées',
    push_sent: 'Relance envoyée',
    report_created: 'Signalement envoyé',
  } as Record<string, string>,
  common: { of: 'sur', none: 'aucun', loading: 'Chargement…', back: 'Retour', today: 'aujourd’hui', week: '7 jours', language: 'Langue', date: 'Date' },
} as const

const number = new Intl.NumberFormat('fr-FR')
const money = new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 })
const euros = new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 2 })
const date = new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' })
const dateTime = new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'UTC' })

export const fmt = {
  n: (v: number) => number.format(v),
  usd: (v: number) => money.format(v),
  eur: (v: number) => euros.format(v),
  pct: (ratio: number | null) => (ratio === null ? 'n/d' : `${Math.round(ratio * 100)} %`),
  date: (iso: string | Date | null) => (iso ? date.format(new Date(iso)) : 'n/d'),
  dateTime: (iso: string | Date | null) => (iso ? dateTime.format(new Date(iso)) : 'n/d'),
  ms: (v: number) => (v >= 1000 ? `${(v / 1000).toFixed(1)} s` : `${Math.round(v)} ms`),
}
